[tool.poetry]
name = "hexlet-code"
version = "0.1.0"
description = ""
authors = ["seeu359 <a.ch3re359@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
flake8 = "^5.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
